# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20160831_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Cancelado'), (1, 'Aprovado'), (0, 'Pendente')], default=1, verbose_name='Situaçao'),
        ),
    ]
