# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20161122_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
