# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20161123_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Meteriais'},
        ),
        migrations.RenameField(
            model_name='material',
            old_name='nome',
            new_name='name',
        ),
    ]
