# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20161123_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprovado'), (2, 'Cancelado'), (0, 'Pendente')], default=1, verbose_name='Situaçao'),
        ),
    ]
